{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "good-chart.fullname" . }}
  labels:
    {{- include "good-chart.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
